name: Build and Deploy (Production)
permissions:
  contents: write
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Setup Node.js 📦
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies 🔧
        run: npm ci --include=dev

      - name: Build code 🚚
        run: npm run build

      - name: Release front-end 🎢
        run: |
          sed -i -e 's/%COMMIT_SHA%/'"${GITHUB_SHA::7}"'/g' packages/ide/src/app/tab-start/tab-start.component.html
          export DATE_NOW_FORMATTED=$(date +'%d/%m/%Y %I:%M:%S %p %Z')
          sed -i -e 's*%DATE%*'"${DATE_NOW_FORMATTED}"'*g' packages/ide/src/app/tab-start/tab-start.component.html
          ./packages/ide/cleanup-icons.sh
          npm run release

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/ide/dist/browser
